Repository traP-jp/traO-Judge-docs, pull requests merged in 2024-10, with the labels that each got.

#15 judgeのapiを書き直した
  api/judge/to_backend.yaml
Labels: bug, enhancement

#23 🐛 add operationId
  api/backend/to_judge.yaml
  api/judge/to_backend.yaml
Labels: bug

#22 🐛 ref naosita
  api/judge/to_backend.yaml
Labels: bug

#26 openapi.yaml向けのCIを追加
  .github/workflows/_backend_api.yml
  .github/workflows/_judge_api.yml
Labels: ci/test

#36 🐛 use symlinkJoin and nix-filter
  exec-container/flake.nix
  exec-container/python/python-3-11.nix
  exec-container/python/python-3-12.nix
  exec-container/python/python-all.nix
  exec-container/utils/bin_flatten.nix
  exec-container/utils/bin_link.nix
Labels: bug

#109 feat: pkgs.dockerToolsを利用する
  exec-container/Dockerfile
  exec-container/compilers/default.nix
  exec-container/docker-image.nix
  exec-container/flake.lock
  exec-container/flake.nix
  exec-container/interpreters/default.nix
  exec-container/interpreters/python/3.11/default.nix
  exec-container/interpreters/python/3.12/default.nix
  exec-container/interpreters/python/default.nix
  exec-container/python/python-3-11.nix
  exec-container/python/python-3-12.nix
  exec-container/python/python-all.nix
Labels: nix

#111 goを追加
  exec-container/compilers/default.nix
  exec-container/compilers/golang/compiler.nix
  exec-container/compilers/golang/default.nix
  exec-container/compilers/golang/go-mod.nix
  exec-container/flake.nix
Labels: enhancement

#113 ✨ brainfuck compiler
  exec-container/compilers/brainfuck/default.nix
  exec-container/compilers/default.nix
Labels: enhancement, nix

#122 nix fmt CI
  .github/workflows/exec-container.yml
  exec-container/interpreters/bash/default.nix
Labels: nix
